# Generated by Django 6.0 on 2026-08-11 10:32

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


def populate_chunk_indexes(apps, schema_editor):
    document_chunk = apps.get_model("docmanage", "DocumentChunk")
    document_ids = (
        document_chunk.objects.order_by()
        .values_list("document_id", flat=True)
        .distinct()
    )

    for document_id in document_ids.iterator():
        chunks = document_chunk.objects.filter(document_id=document_id).order_by("id")
        for chunk_index, chunk_id in enumerate(
            chunks.values_list("id", flat=True).iterator()
        ):
            document_chunk.objects.filter(id=chunk_id).update(chunk_index=chunk_index)


class Migration(migrations.Migration):
    dependencies = [
        ("docmanage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="documentchunk",
            options={"ordering": ("document_id", "chunk_index")},
        ),
        migrations.AddField(
            model_name="document",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="size_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="content_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="page_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.RunPython(populate_chunk_indexes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("owner", "content_hash"),
                name="unique_document_content_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("document", "chunk_index"),
                name="unique_chunk_index_per_document",
            ),
        ),
    ]
